/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AppIdentityRole { 
    Id?: number;
    Name?: string | null;
    NormalizedName?: string | null;
    ConcurrencyStamp?: string | null;
    Description?: string | null;
    AllowsRequest?: boolean;
    RequiresApproval?: boolean;
    MaxRoleRequestCount?: number;
    MaxRoleGrantCount?: number;
}

