/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppIdentityUser } from './appIdentityUser';


export interface AppIdentityRefreshToken { 
    RefreshTokenID?: string;
    IssuedUTC?: Date;
    ExpiresUTC?: Date;
    TokenValue: string;
    UserId?: number;
    User?: AppIdentityUser;
}

