/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthorizationAsset { 
    AssetID?: number;
    RouteURL?: string | null;
    AssetName?: string | null;
    AssetTypeID?: number;
    AssetDesc?: string | null;
    UnauthenticatedBehaviorID?: number;
    UnauthenticatedFailoverRoute?: string | null;
    UnauthorizedBehaviorID?: number;
    UnauthorizedFailoverRoute?: string | null;
    RoleID?: number;
    UserID?: number;
    Authorized?: boolean;
}

