/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tag } from './tag';


export interface ContextNote { 
    NoteID?: number;
    Context?: string | null;
    ContextKey?: number;
    NoteSubject?: string | null;
    NoteContent?: string | null;
    NoteEntryUTC?: Date;
    NoteTypeID?: number;
    NoteTypeName?: string | null;
    SortOrder?: number;
    Tags?: Array<Tag> | null;
}

