/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContextEquipmentAttachmentDetail { 
    CEAID?: string;
    CEID?: number;
    Context?: string | null;
    ContextKey?: number;
    Active?: boolean;
    RecommendationLevelID?: number;
    AttachmentAddedUTC?: Date;
    AttachmentLastUpdatedUTC?: Date;
    ContextName?: string | null;
    RecommendationLevelName?: string | null;
    Recommended?: boolean;
    Required?: boolean;
}

