/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContextGlossaryAutoComplete { 
    Context?: string | null;
    ContextKey?: number;
    CGID?: number;
    Term?: string | null;
    Synonyms?: string | null;
    Definition?: string | null;
    ApplicationCount?: number;
}

