/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContactAddress { 
    AddressHistoryID?: number;
    ContactID?: number;
    AddressTitle?: string | null;
    Address1?: string | null;
    Address2?: string | null;
    AddressAptSuite?: string | null;
    City?: string | null;
    State?: string | null;
    ZipCode?: string | null;
    Nation?: string | null;
    IsPrimary?: boolean;
    TenantID?: number;
}

