/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContextQuizAnswer } from './contextQuizAnswer';


export interface ContextQuizResult { 
    QuizCompletionID?: number;
    ContextQuestionID?: number;
    QuizCompletionQuestionID?: number;
    WasSkipped?: boolean;
    WasAnswered?: boolean;
    WasCorrect?: boolean;
    WasBestAnswer?: boolean;
    PointsAwarded?: number;
    Tries?: number;
    ElapsedTimeSeconds?: number;
    ChosenAnswer?: ContextQuizAnswer;
    ChosenAnswers?: Array<ContextQuizAnswer> | null;
}

