/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContextEquipmentAutoComplete { 
    Context?: string | null;
    ContextKey?: number;
    CEID?: number;
    EquipmentName?: string | null;
    EquipmentDesc?: string | null;
    ApplicationCount?: number;
}

