/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContextLinkAttachmentDetail } from './contextLinkAttachmentDetail';


export interface ContextLinkEntryForDisplay { 
    CLID?: number;
    ContextLinkAttachmentID?: string;
    Context?: string | null;
    ContextKey?: number;
    Title?: string | null;
    Desc?: string | null;
    URL?: string | null;
    LinkIssue?: boolean;
    LinkDead?: boolean;
    AddedUTC?: Date;
    LastUpdatedUTC?: Date;
    AttachmentAddedUTC?: Date;
    AttachmentLastUpdatedUTC?: Date;
    IsNew?: boolean;
    IsUpdated?: boolean;
    AttachmentCount?: number;
    ContextAttachments?: Array<ContextLinkAttachmentDetail> | null;
}

