/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContextMediaDetail { 
    ContextMediaID?: number;
    Context?: string | null;
    ContextKey?: number;
    MediaTypeID?: number;
    MediaTypeName?: string | null;
    MediaLocationID?: number;
    MediaLocationName?: string | null;
    MediaLocationURL?: string | null;
    IsImage?: boolean;
    IsMoving?: boolean;
    IsVideo?: boolean;
    IsAudio?: boolean;
    IsLink?: boolean;
    MediaStatusID?: number;
    MediaStatusName?: string | null;
    Placeholder?: boolean;
    InDevelopment?: boolean;
    Released?: boolean;
    ExcludedDoNotDisplayExternally?: boolean;
    Resolution?: string | null;
    TacticalUsage?: string | null;
    MediaUsageTypeID?: number;
    MediaUsageTypeName?: string | null;
    Title?: string | null;
    Caption?: string | null;
    Attribution?: string | null;
    AttributionURL?: string | null;
    AllowAudio?: boolean;
    AutoPlay?: boolean;
    AllowFullscreenExpansion?: boolean;
    FileNameOriginal?: string | null;
    FileName?: string | null;
    FileSizeKB?: number;
    IsDefault?: boolean;
    OptimizationRequired?: boolean;
    SortOrder?: number;
    RemotelyHosted?: boolean;
    RemotelyURL?: string | null;
    LegacyFileName?: string | null;
    LegacyFileID?: number;
    LegacyMediaIndex?: number;
    ProfileFrameID?: number;
    ProfileSpeedID?: number;
    ProfileResolutionID?: number;
    ProfileQualityID?: number;
    ProfileColorModeID?: number;
    HasCover?: boolean;
    CoverFileName?: string | null;
    HasCoverBlur?: boolean;
    CoverBlurFileName?: string | null;
    HasError?: boolean;
    ErrorInfo?: string | null;
    Width?: number;
    Height?: number;
    HeightAdjRatio?: number;
    WidthAdjRatio?: number;
}

