/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContextQuizQuestion } from './contextQuizQuestion';
import { QuizConstraints } from './quizConstraints';
import { IQuizQuestionState } from './iQuizQuestionState';
import { QuizPointState } from './quizPointState';
import { ContextEntry } from './contextEntry';


export interface ContextQuiz { 
    ContextQuizName?: string | null;
    ContextQuizDesc?: string | null;
    ContextQuizDescriptors?: string | null;
    DifficultyLevelID?: number;
    Context?: ContextEntry;
    Questions?: Array<ContextQuizQuestion> | null;
    QuestionState?: IQuizQuestionState;
    PointState?: QuizPointState;
    Constraints?: QuizConstraints;
    ContextIncomplete?: boolean;
    ContextUnsuccessful?: boolean;
    TimeAllowedSeconds?: number;
    TimeWarningSeconds?: number;
}

