/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContextSidebar { 
    ContextSidebarID?: number;
    Context?: string | null;
    ContextKey?: number;
    SidebarTarget?: string | null;
    SidebarText?: string | null;
    SidebarColor?: string | null;
    SidebarBackgroundColor?: string | null;
    SidebarBorderStyle?: string | null;
}

