/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContextMetric { 
    Context?: string | null;
    ContextKey?: number;
    ContextName?: string | null;
    Metric?: string | null;
    FocusTenantID?: number;
    FocusUserID?: number;
    Usage?: number;
    LastVisitUTC?: Date;
    CFocusDate?: Date;
    CFocusHour?: number;
    CFocusWeekDay?: number;
    CFocusWeek?: number;
    CFocusMonth?: number;
}

