/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TechniqueShort } from './techniqueShort';


export interface CurriculumPartDetail { 
    CurriculumPartID?: number;
    CurriculumID?: number;
    CurriculumPartName?: string | null;
    CurriculumPartPurpose?: string | null;
    CurriculumPartNarrative?: string | null;
    CurriculumPartStatusID?: number;
    CurriculumPartStatusName?: string | null;
    ShowPublic?: boolean;
    ShowPrivate?: boolean;
    Ready?: boolean;
    NotReady?: boolean;
    SortOrder?: number;
    Application?: Array<TechniqueShort> | null;
}

