/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CurriculumStatusEntry { 
    CurriculumStatusID?: number;
    CurriculumStatusName?: string | null;
    ShowPublic?: boolean;
    ShowPrivate?: boolean;
    Ready?: boolean;
    NotReady?: boolean;
}

