/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DecisionNode { 
    NodeID?: number;
    FlowID?: number;
    NodeName?: string | null;
    NodeNameFormatted?: string | null;
    NodeNameSantitized?: string | null;
    SanitizingDifferences?: boolean;
    NodeTypeID?: number;
    NodeTypeName?: string | null;
    DagreShapeName?: string | null;
    ShapeID?: number;
    ShapeName?: string | null;
    NodeTooltipTitle?: string | null;
    NodeTooltipContent?: string | null;
    NodeTooltipURL?: string | null;
    NodeDesc?: string | null;
    NodeHeightOverride?: string | null;
    NodeWidthOverride?: string | null;
    IsOpening?: boolean;
    IsTerminating?: boolean;
    ForegroundColorRGB?: string | null;
    BackgroundColorRGB?: string | null;
    DrawingColorRGB?: string | null;
    HttpRef?: string | null;
    HyperLinkRef?: string | null;
    HyperLinkOpenVia?: string | null;
    HyperLinkFlowID?: number;
    HyperLinkApplicationKey?: string | null;
    HyperlinkTarget?: string | null;
    FillStyle?: string | null;
    LineStyleList?: string | null;
    Identifier?: string | null;
    CssClass?: string | null;
    NodeAttributes?: string | null;
    DrilldownID?: number;
    TransferID?: number;
    ColorScheme?: string | null;
    ColorSchemeColor?: string | null;
}

