/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DecisionClusterNode } from './decisionClusterNode';


export interface DecisionCluster { 
    ClusterID?: number;
    FlowID?: number;
    ClusterName?: string | null;
    ClusterLabel?: string | null;
    ClusterDesc?: string | null;
    ForegroundColorRGB?: string | null;
    BackgroundColorRGB?: string | null;
    DrawingColorRGB?: string | null;
    FillStyle?: string | null;
    LineStyleList?: string | null;
    FontName?: string | null;
    FontSize?: string | null;
    CssClass?: string | null;
    Identifier?: string | null;
    LabelJustification?: string | null;
    ColorScheme?: string | null;
    ColorSchemeColor?: string | null;
    ClusterAttributes?: string | null;
    SharedNodeAttributes?: string | null;
    SharedEdgeAttributes?: string | null;
    Nodes?: Array<DecisionClusterNode> | null;
}

