/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EffectiveTenantIPConfig } from './effectiveTenantIPConfig';
import { EffectiveTenantUserRole } from './effectiveTenantUserRole';
import { EffectiveTenantRole } from './effectiveTenantRole';
import { EffectiveTenantKey } from './effectiveTenantKey';
import { EffectiveTenantDomain } from './effectiveTenantDomain';
import { EffectiveTenantSubscription } from './effectiveTenantSubscription';
import { EffectiveTenantHostname } from './effectiveTenantHostname';
import { EffectiveTenantQueryString } from './effectiveTenantQueryString';


export interface EffectiveTenantUser { 
    TenantUserID?: string;
    UserID?: number;
    IsDefaultTenant?: boolean;
    TenantID?: number;
    SortOrder?: number;
    AddedUTC?: Date;
    AddedByUserID?: number;
    TenantUserEffectivenessID?: string;
    TenantName?: string | null;
    UserName?: string | null;
    PreferredFullName?: string | null;
    PhoneNumber?: string | null;
    Email?: string | null;
    EffectiveUTC?: Date;
    ExpirationUTC?: Date;
    Notes?: string | null;
    Domains?: Array<EffectiveTenantDomain> | null;
    IPConfig?: Array<EffectiveTenantIPConfig> | null;
    Hostnames?: Array<EffectiveTenantHostname> | null;
    QueryStrings?: Array<EffectiveTenantQueryString> | null;
    Keys?: Array<EffectiveTenantKey> | null;
    Roles?: Array<EffectiveTenantRole> | null;
    UserRoles?: Array<EffectiveTenantUserRole> | null;
    Subscriptions?: Array<EffectiveTenantSubscription> | null;
}

