/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EffectiveTenantUserRole { 
    UserRoleEffectivenessID?: string;
    UserRoleID?: string;
    RoleID?: number;
    RoleName?: string | null;
    UserID?: number;
    UserName?: string | null;
    PreferredFullName?: string | null;
    TenantID?: number;
    TenantName?: string | null;
    Approved?: boolean;
    ApprovedByUserID?: number;
    ApprovedOnUTC?: Date;
    RequiredApproval?: boolean;
    DeniedByUserID?: number;
    DeniedOnUTC?: Date;
    DeniedReason?: string | null;
    RevokedByUserID?: number;
    RevokedOnUTC?: Date;
    RevokeReason?: string | null;
    EffectiveUTC?: Date;
    ExpirationUTC?: Date;
}

