/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IPComparisonModeEnum } from './iPComparisonModeEnum';


export interface EffectiveTenantIPConfig { 
    IPConfigID?: string;
    TenantID?: number;
    IPComparisonMode?: IPComparisonModeEnum;
    IPAddress?: string | null;
    PortNumber?: number;
    IPConfigEffectivenessID?: string;
    EffectiveUTC?: Date;
    ExpirationUTC?: Date;
}

