/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmailPayload { 
    FromEmailAddress?: string | null;
    FromName?: string | null;
    To?: Array<string> | null;
    CC?: Array<string> | null;
    BCC?: Array<string> | null;
    Subject?: string | null;
    Body?: string | null;
}

