/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileUploadVerification { 
    FileName?: string | null;
    FileSizeBytes?: number;
    FilePath?: string | null;
    FileExtension?: string | null;
    FileType?: string | null;
    ReturnVal?: number;
    ReturnMsg?: string | null;
}

