/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormationElement } from './formationElement';
import { FormationPoint } from './formationPoint';


export interface Formation { 
    FormationID?: number;
    FormationName?: string | null;
    FormationDesc?: string | null;
    FormationFile?: string | null;
    FieldSizeID?: number;
    TenantID?: number;
    UserID?: number;
    AddedByUserID?: number;
    AddedUTC?: Date;
    Points?: Array<FormationPoint> | null;
    Elements?: Array<FormationElement> | null;
}

