/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TechniqueKeyMap } from './techniqueKeyMap';


export interface GenericTreeNode { 
    KeyValue?: TechniqueKeyMap;
    SourceObject?: any | null;
    ObjectType?: string | null;
    ParentID?: string | null;
    ID?: string | null;
    Level?: number;
    Text?: string | null;
    Desc?: string | null;
    Abbrev?: string | null;
    Children?: Array<GenericTreeNode> | null;
}

