/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvitationDetail { 
    InvitationID?: number;
    TenantID?: number;
    HostUserID?: number;
    Description?: string | null;
    GuestEmailAddress?: string | null;
    GuestNameFirst?: string | null;
    GuestNameLast?: string | null;
    GuestPhoneNumber?: string | null;
    AddedUTC?: Date;
    AddedLocalDT?: Date;
    AcceptedUTC?: Date;
    AcceptedLocalDT?: Date;
    GuestUserID?: number;
    PointValue?: number;
    Context?: string | null;
    ContextKey?: number;
    InvitationMessage?: string | null;
    WelcomeMessage?: string | null;
    WelcomeVisitMade?: boolean;
    AccountCreated?: boolean;
    ProviderName?: string | null;
    ProviderTypeName?: string | null;
    InvitationStatusID?: number;
    InvitationStatusName?: string | null;
    InvitationSortIndex?: number;
    RosterCountValue?: number;
    InvitationActive?: boolean;
    InvitationInProcess?: boolean;
    InvitationInactive?: boolean;
    InvitationPending?: boolean;
    InvitationIn?: boolean;
    InvitationTBD?: boolean;
    InvitationOut?: boolean;
}

