/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MailingListEntry { 
    MailingListID?: number;
    MailingListContext?: string | null;
    MailingListContextKey?: number;
    MailingListContextFriendlyName?: string | null;
    NameFirst?: string | null;
    NameLast?: string | null;
    EmailAddress?: string | null;
    PhoneNumber?: string | null;
    Address1?: string | null;
    Address2?: string | null;
    City?: string | null;
    State?: string | null;
    ZipCode?: string | null;
    AddedUTC?: Date;
    AddedVia?: string | null;
    IsCurrent?: boolean;
    IsValidPhone?: boolean;
    IsValidEmail?: boolean;
    IsValidMailing?: boolean;
    RemovedUTC?: Date;
    RemovedVia?: string | null;
}

