/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PracticePlanFlatApplication { 
    readonly ObjectType?: string | null;
    Level?: number;
    PPTID?: number;
    PracticePlanID?: number;
    TechniqueID?: number;
    TechniqueName?: string | null;
    TechniqueTypeID?: number;
    TechniqueTypeName?: string | null;
    TechniqueStatusID?: number;
    TechniqueStatusName?: string | null;
    ShortDescription?: string | null;
    Synonyms?: string | null;
    TacticalUsage?: string | null;
    History?: string | null;
    Description?: string | null;
    Cue?: string | null;
    AntiPatterns?: string | null;
    SkillLevelID?: number;
    SkillLevelName?: string | null;
    DifficultyLevelID?: number;
    DifficultyLevelName?: string | null;
    ReliabilityLevelID?: number;
    ReliabilityLevelName?: string | null;
    RiskLevelID?: number;
    RiskLevelName?: string | null;
    AddedByContributorID?: number;
    RequiresReview?: boolean;
    RequiresContentChanges?: boolean;
    RequiresMedia?: boolean;
    RequiresAdminApproval?: boolean;
    Released?: boolean;
    BetaMarker?: boolean;
    LegendColor?: string | null;
    TechniqueTypeStatusID?: number;
    TechniqueTypeStatusName?: string | null;
    TechniqueClassID?: number;
    TechniqueClassName?: string | null;
    PositionID?: number;
    PositionName?: string | null;
    PositionNumber?: number;
    TechniqueTypeIndex?: number;
    LegacyFileName?: string | null;
    LegacyFileID?: number;
    SportID?: number;
    SportName?: string | null;
    SportAbbrev?: string | null;
    PatternTypeID?: number;
    PatternTypeName?: string | null;
    PatternTypeAlt?: string | null;
    PatternTypeScore?: number;
    SortOrder?: number;
    ContentTypeID?: number;
    ContentTypeName?: string | null;
    IsGraphicsAssisted?: boolean;
    IsTextOnly?: boolean;
    IsDiagramAssisted?: boolean;
    AcquisitionMethodID?: number;
    AcquisitionMethodName?: string | null;
    AcquisitionMethodShort?: string | null;
    AcquisitionMethodDesc?: string | null;
    InstructionMethodID?: number;
    InstructionMethodName?: string | null;
    DirectInstruction?: boolean;
    IndirectInstruction?: boolean;
    InstructionGoal?: string | null;
    ShowPaceMediaControls?: boolean;
    ShowTimerControls?: boolean;
    ShowQuizControls?: boolean;
    ShowColorFlash?: boolean;
    IsNew?: boolean;
    TSID?: number;
    TechniqueSeriesName?: string | null;
    TSIndex?: number;
    Descriptors?: string | null;
    StandAloneGroupName?: string | null;
    TAID?: number;
    IsTechniqueTemplate?: boolean;
    ProfileMediaIndex?: number;
    MuscleGroupID?: number;
    MuscleGroupName?: string | null;
    MuscleGroupLatin?: string | null;
    MuscleGroupLevel?: string | null;
    ExerciseClassID?: number;
    ExerciseClassName?: string | null;
    EngagementMechanismID?: number;
    EngagementMechanismName?: string | null;
    PossessionStateID?: number;
    PossessionStateName?: string | null;
    PossessionStateDesc?: string | null;
    PossessionStateAbbrev?: string | null;
    SectionID?: number;
    SectionName?: string | null;
    SectionDesc?: string | null;
    SharingContextTypeID?: number;
    SharingContextTypeName?: string | null;
    SharingContextKey?: number;
    IsPublic?: boolean;
    IsPrivateForTeam?: boolean;
    IsPrivateForTeamGroup?: boolean;
    IsPrivateForTeamMember?: boolean;
    IsPrivateForUser?: boolean;
    IsPrivateForPracticePlan?: boolean;
    ChildCount?: number;
    ChildrenVisible?: boolean;
    IsVisible?: boolean;
}

