/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PracticePlanApplicationTreeTechnique { 
    PPTID?: number;
    PracticePlanID?: number;
    SportID?: number;
    SportName?: string | null;
    SportAbbrev?: string | null;
    TechniqueClassID?: number;
    TechniqueClassName?: string | null;
    TechniqueTypeID?: number;
    TechniqueTypeName?: string | null;
    PositionID?: number;
    PositionName?: string | null;
    TSID?: number;
    TechniqueSeriesName?: string | null;
    MuscleGroupID?: number;
    MuscleGroupName?: string | null;
    MuscleGroupLatin?: string | null;
    MuscleGroupLevel?: string | null;
    ExerciseClassID?: number;
    ExerciseClassName?: string | null;
    EngagementMechanismID?: number;
    EngagementMechanismName?: string | null;
    PossessionStateID?: number;
    PossessionStateName?: string | null;
    PossessionStateDesc?: string | null;
    PossessionStateAbbrev?: string | null;
    TechniqueID?: number;
    TechniqueName?: string | null;
    ShortDescription?: string | null;
    TechniqueStatusID?: number;
    TechniqueStatusName?: string | null;
    BetaMarker?: boolean;
    LegendColor?: string | null;
    ApplicationCount?: number;
    AccessibilityCount?: number;
    MediaCount?: number;
    PatternTypeID?: number;
    PatternTypeName?: string | null;
    PatternTypeAlt?: string | null;
    PatternTypeScore?: number;
    AcquisitionMethodID?: number;
    AcquisitionMethodName?: string | null;
    AcquisitionMethodShort?: string | null;
    AcquisitionMethodDesc?: string | null;
}

