/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoutingDetail { 
    RoutingModuleID?: number;
    RoutingModuleMenuID?: number;
    RoutingModuleMenuSectionID?: number;
    RouteText?: string | null;
    RouteDesc?: string | null;
    RoutePath?: string | null;
    RouteComponentType?: string | null;
    DataJSON?: string | null;
    RoutingModuleMenuSortOrder?: number;
    RouteSortOrder?: number;
    TechniqueCount?: number;
    ModuleIsActive?: boolean;
    MenuIsActive?: boolean;
    RouteIsActive?: boolean;
}

