/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SportsTrashTalk { 
    TrashTalkID?: number;
    TrashTalkContent?: string | null;
    TrashTalkAttributionName?: string | null;
    TrashTalkAttributionContext?: string | null;
    TrashTalkMeaning?: string | null;
    AddedUTC?: Date;
    AddedByUserID?: number;
    TrashTalkTags?: string | null;
    TrashTalkUsage?: number;
    ApplicationCount?: number;
}

