/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SportPositionSpiderChartEvaluationType { 
    EvaluationTypeID?: number;
    EvaluationTypeName?: string | null;
    EvaluationClassID?: number;
    PositionID?: number;
    IsActive?: boolean;
    IsRequired?: boolean;
    MinValue?: number;
    MaxValue?: number;
    DefaultValue?: number;
    PositionEvaluationRequirementID?: number;
    PositionEvaluationDataPointID?: number;
    EvaluationTypeValueID?: number;
    EvaluationTypeValueName?: string | null;
    EvaluationTypeValueDesc?: string | null;
}

