/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SportsQuote { 
    QuoteID?: number;
    QuoteContent?: string | null;
    QuoteAttributionName?: string | null;
    QuoteAttributionContext?: string | null;
    QuoteMeaning?: string | null;
    AddedUTC?: Date;
    AddedByUserID?: number;
    QuoteTags?: string | null;
    QuoteUsage?: number;
    ApplicationCount?: number;
    AuthorID?: number;
    AuthorDesc?: string | null;
    AuthorHistoricalContext?: string | null;
    AuthorWikiURL?: string | null;
}

