/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubscriptionStatus { 
    SubscriptionStatusID?: number;
    SubscriptionStatusName?: string | null;
    Signed?: boolean;
    Active?: boolean;
    Hold?: boolean;
    Expired?: boolean;
    IsDateSensitive?: boolean;
}

