/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TechniqueApplication { 
    TAID?: number;
    TechniqueID?: number;
    TechniqueClassID?: number;
    TechniqueClassName?: string | null;
    TechniqueTypeID?: number;
    TechniqueTypeName?: string | null;
    FormationID?: number;
    FormationName?: string | null;
    FormationClass?: string | null;
    TechniqueTypeIndex?: number;
    SortOrder?: number;
    TSID?: number;
    TechniqueSeriesName?: string | null;
    TSIndex?: number;
    MuscleGroupID?: number;
    MuscleGroupName?: string | null;
    MuscleGroupLatin?: string | null;
    ExerciseClassID?: number;
    ExerciseClassName?: string | null;
    EngagementMechanismID?: number;
    EngagementMechanismName?: string | null;
    PossessionStateID?: number;
    PossessionStateName?: string | null;
    PossessionStateDesc?: string | null;
    PossessionStateAbbrev?: string | null;
    PitchPositionID?: number;
    PitchPositionName?: string | null;
    PitchPositionNameAlternate?: string | null;
    PitchPositionAbbrev?: string | null;
    PitchPositionDesc?: string | null;
    PitchPositionSortOrder?: number;
    AlternateTechniqueName?: string | null;
    NodeTechniqueCrossoverExists?: boolean;
    KeyTechnique?: boolean;
}

