/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TechniqueAutoComplete { 
    TechniqueID?: number;
    TechniqueName?: string | null;
    TechniqueTypeID?: number;
    TechniqueTypeName?: string | null;
    ShortDescription?: string | null;
    SportID?: number;
    SportName?: string | null;
    SportAbbrev?: string | null;
    TechniqueStatusID?: number;
    TechniqueStatusName?: string | null;
    BetaMarker?: boolean;
    LegendColor?: string | null;
    PatternTypeID?: number;
    PatternTypeName?: string | null;
    PatternTypeAlt?: string | null;
    PatternTypeScore?: number;
}

