/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TechniqueForUpdate { 
    TechniqueID?: number;
    SportID?: number;
    PatternTypeID?: number;
    ContentTypeID?: number;
    TechniqueStatusID?: number;
    TechniqueName?: string | null;
    StandAloneGroupName?: string | null;
    ShortDescription?: string | null;
    Synonyms?: string | null;
    TacticalUsage?: string | null;
    History?: string | null;
    Description?: string | null;
    Cue?: string | null;
    AntiPatterns?: string | null;
    SkillLevelID?: number;
    DifficultyLevelID?: number;
    ReliabilityLevelID?: number;
    RiskLevelID?: number;
    AddedUTC?: Date;
    AddedByContributorID?: number;
    LastUpdatedUTC?: Date;
    LastUpdatedByContributorID?: number;
    LegacyFileName?: string | null;
    LegacyFileID?: number;
    IsTechniqueTemplate?: boolean;
    IsPracticePlanEligible?: boolean;
    AcquisitionMethodID?: number;
    InstructionMethodID?: number;
    InstructionGoal?: string | null;
    PracticeModeratorSideID?: number;
    PracticeModeratorPlayerMovementID?: number;
    PracticeModeratorBallMovementID?: number;
    PracticeModeratorRotationID?: number;
    PointValue?: number;
    ShowPaceMediaControls?: boolean;
    ShowTimerControls?: boolean;
    ShowQuizControls?: boolean;
    ShowColorFlash?: boolean;
    Descriptors?: string | null;
    CopyOfTechniqueID?: number;
    ProfileMediaIndex?: number;
    CurationNotes?: string | null;
}

