/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TechniquePhase { 
    TacticalPhaseID?: number;
    TacticalPhaseName?: string | null;
    PhaseTypeOffensive?: boolean;
    PeriodTypeDefensive?: boolean;
    PeriodTypeOrganized?: boolean;
    PeriodTypeDisorganized?: boolean;
    NotApplied?: boolean;
    TPID?: number;
    TechniqueID?: number;
    SortOrder?: number;
}

