/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TechniqueType } from './techniqueType';
import { ContextMediaDetail } from './contextMediaDetail';


export interface TechniqueClass { 
    TechniqueClassID?: number;
    TechniqueClassName?: string | null;
    TechniqueClassDesc?: string | null;
    TechniqueClassStatusID?: number;
    TechniqueClassStatusName?: string | null;
    IsTechniqueClassActiveDevelopmentWIP?: boolean;
    MenuIndicator?: string | null;
    MenuHint?: string | null;
    SportID?: number;
    SportName?: string | null;
    IsGeneral?: boolean;
    IsPositionBased?: boolean;
    IsFormationBased?: boolean;
    OrientationPlayerDevelopment?: boolean;
    OrientationNonPlayerDevelopment?: boolean;
    SortOrder?: number;
    PointValue?: number;
    ClassTypesAreSectioned?: boolean;
    SectionCount?: number;
    Media?: Array<ContextMediaDetail> | null;
    TechniqueTypes?: Array<TechniqueType> | null;
}

