/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TechniqueTypeForGuidance } from './techniqueTypeForGuidance';


export interface TechniqueClassForGuidance { 
    TechniqueClassID?: number;
    TechniqueClassName?: string | null;
    TechniqueClassDesc?: string | null;
    TechniqueClassStatusID?: number;
    TechniqueClassStatusName?: string | null;
    MenuIndicator?: string | null;
    MenuHint?: string | null;
    SportID?: number;
    SportName?: string | null;
    IsGeneral?: boolean;
    IsPositionBased?: boolean;
    OrientationPlayerDevelopment?: boolean;
    OrientationNonPlayerDevelopment?: boolean;
    SortOrde?: number;
    PointValue?: number;
    TechniqueTypes?: Array<TechniqueTypeForGuidance> | null;
}

