/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TechniqueShort } from './techniqueShort';


export interface TechniqueApplicationSeriesForTechniqueEditor { 
    TSVLID?: number;
    TSID?: number;
    TechniqueSeriesName?: string | null;
    TechniqueSeriesSubtitle?: string | null;
    TechniqueSeriesAbbrev?: string | null;
    TechniqueSeriesDesc?: string | null;
    TechniqueSeriesIndex?: number;
    SportID?: number;
    SportName?: string | null;
    TechniqueClassID?: number;
    TechniqueClassName?: string | null;
    TechniqueTypeID?: number;
    TechniqueTypeName?: string | null;
    TechniqueApplicationSeriesStatusID?: number;
    TechniqueApplicationSeriesStatusName?: string | null;
    IsPublicReady?: boolean;
    IsPublic?: boolean;
    IsTechniqueApplicationSeriesActiveDevelopmentWIP?: boolean;
    UsageCount?: number;
    HasQuiz?: boolean;
    IsVirtualLink?: boolean;
    MuscleGroupID?: number;
    ParentMuscleGroupID?: number;
    MuscleGroupName?: string | null;
    MuscleGroupLatin?: string | null;
    MuscleGroupDesc?: string | null;
    MuscleGroupLevel?: number;
    MuscleChainID?: number;
    MuscleChainName?: string | null;
    MuscleChainDesc?: string | null;
    RecommendedWeeklyTrainingFrequency?: number;
    ExerciseClassID?: number;
    ExerciseClassName?: string | null;
    IsBodyDevelopment?: boolean;
    IsMindDevelopment?: boolean;
    IsPositionBased?: boolean;
    OrientationPlayerDevelopment?: boolean;
    OrientationNonPlayerDevelopment?: boolean;
    IsGeneral?: boolean;
    IsSpecialProjects?: boolean;
    KeySeries?: boolean;
    Techniques?: Array<TechniqueShort> | null;
}

