/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TechniqueApplicationSeriesForTechniqueEditor } from './techniqueApplicationSeriesForTechniqueEditor';
import { TechniqueShort } from './techniqueShort';
import { ContextMediaDetail } from './contextMediaDetail';


export interface TechniqueType { 
    TechniqueTypeID?: number;
    TechniqueTypeStatusID?: number;
    TechniqueTypeName?: string | null;
    TechniqueTypeSubtitle?: string | null;
    TechniqueTypeDesc?: string | null;
    TechniqueClassID?: number;
    TechniqueClassSectionID?: number;
    TechniqueClassSectionName?: string | null;
    SortOrder?: number;
    FileImportHelper?: string | null;
    MenuHint?: string | null;
    Representative?: string | null;
    TechniqueTypeStatusName?: string | null;
    IsTechniqueTypeActiveDevelopmentWIP?: boolean;
    SportID?: number;
    SportName?: string | null;
    IsPublicReady?: boolean;
    IsPublic?: boolean;
    IsGeneral?: boolean;
    IsMindDevelopment?: boolean;
    IsPositionBased?: boolean;
    IsSpecialProjects?: boolean;
    OrientationPlayerDevelopment?: boolean;
    OrientationNonPlayerDevelopment?: boolean;
    TechniqueCount?: number;
    TechniqueApplicationSeriesCount?: number;
    TechniqueApplicationSeries?: Array<TechniqueApplicationSeriesForTechniqueEditor> | null;
    Techniques?: Array<TechniqueShort> | null;
    Media?: Array<ContextMediaDetail> | null;
}

