/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TechniqueSeriesNavigationDetail { 
    SportID?: number;
    SportName?: string | null;
    TechniqueClassID?: number;
    TechniqueClassName?: string | null;
    TechniqueTypeID?: number;
    TechniqueTypeName?: string | null;
    PositionID?: number;
    PositionName?: string | null;
    TSID?: number;
    TechniqueSeriesName?: string | null;
    TTRow?: number;
    TSRow?: number;
    FirstTechniqueTypeID?: number;
    FirstTechniqueTypeName?: string | null;
    PrevTechniqueTypeID?: number;
    PrevTechniqueTypeName?: string | null;
    NextTechniqueTypeID?: number;
    NextTechniqueTypeName?: string | null;
    LastTechniqueTypeID?: number;
    LastTechniqueTypeName?: string | null;
    FirstTSID?: number;
    FirstTechniqueSeriesName?: string | null;
    PrevTSID?: number;
    PrevTechniqueSeriesName?: string | null;
    NextTSID?: number;
    NextTechniqueSeriesName?: string | null;
    LastTSID?: number;
    LastTechniqueSeriesName?: string | null;
}

