/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AchievementGuidance } from './achievementGuidance';


export interface TechniqueTypeForGuidance { 
    TechniqueTypeID?: number;
    TechniqueTypeStatusID?: number;
    TechniqueTypeName?: string | null;
    TechniqueTypeDesc?: string | null;
    TechniqueClassID?: number;
    SortOrder?: number;
    FileImportHelper?: string | null;
    MenuHint?: string | null;
    SportID?: number;
    Guidance?: Array<AchievementGuidance> | null;
}

