/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TechniqueApplicationUpdate { 
    TAID?: number;
    TechniqueID?: number;
    TechniqueTypeID?: number;
    PossessionStateID?: number | null;
    PitchPositionID?: number | null;
    TechniqueTypeIndex?: number | null;
    SortOrder?: number | null;
    TSID?: number | null;
    TSINDEX?: number | null;
    MuscleGroupID?: number | null;
    ExerciseClassID?: number | null;
    EngagementMechanismID?: number | null;
    FormationID?: number | null;
    AlternateTechniqueName?: string | null;
    KeyTechnique?: boolean;
}

