/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TechniqueAgeGroupDetail { 
    TechniqueID?: number;
    TechniqueAgeGroupID?: number;
    AgeGroupID?: number;
    AgeGroup?: string | null;
    AgeGroupDisplay?: string | null;
    AgeBarrier?: number;
    MinimumAge?: number;
    Minor?: boolean;
    SortOrder?: number;
    PreferredYearCurrent?: number;
    PreferredYearPrev?: number;
    IsSelected?: boolean;
    AchievementExpectationID?: number;
    AchievementExpectationName?: string | null;
}

