export * from './administration.service';
import { AdministrationService } from './administration.service';
export * from './administration.serviceInterface';
export * from './appRouting.service';
import { AppRoutingService } from './appRouting.service';
export * from './appRouting.serviceInterface';
export * from './authenticator.service';
import { AuthenticatorService } from './authenticator.service';
export * from './authenticator.serviceInterface';
export * from './authorization.service';
import { AuthorizationService } from './authorization.service';
export * from './authorization.serviceInterface';
export * from './autocomplete.service';
import { AutocompleteService } from './autocomplete.service';
export * from './autocomplete.serviceInterface';
export * from './betaFeatures.service';
import { BetaFeaturesService } from './betaFeatures.service';
export * from './betaFeatures.serviceInterface';
export * from './body.service';
import { BodyService } from './body.service';
export * from './body.serviceInterface';
export * from './contactMe.service';
import { ContactMeService } from './contactMe.service';
export * from './contactMe.serviceInterface';
export * from './contacts.service';
import { ContactsService } from './contacts.service';
export * from './contacts.serviceInterface';
export * from './contextAccessibilty.service';
import { ContextAccessibiltyService } from './contextAccessibilty.service';
export * from './contextAccessibilty.serviceInterface';
export * from './contextAutocomplete.service';
import { ContextAutocompleteService } from './contextAutocomplete.service';
export * from './contextAutocomplete.serviceInterface';
export * from './contextEquipment.service';
import { ContextEquipmentService } from './contextEquipment.service';
export * from './contextEquipment.serviceInterface';
export * from './contextGlossary.service';
import { ContextGlossaryService } from './contextGlossary.service';
export * from './contextGlossary.serviceInterface';
export * from './contextHelp.service';
import { ContextHelpService } from './contextHelp.service';
export * from './contextHelp.serviceInterface';
export * from './contextLink.service';
import { ContextLinkService } from './contextLink.service';
export * from './contextLink.serviceInterface';
export * from './contextMedia.service';
import { ContextMediaService } from './contextMedia.service';
export * from './contextMedia.serviceInterface';
export * from './contextMetrics.service';
import { ContextMetricsService } from './contextMetrics.service';
export * from './contextMetrics.serviceInterface';
export * from './contextNotes.service';
import { ContextNotesService } from './contextNotes.service';
export * from './contextNotes.serviceInterface';
export * from './contextQuiz.service';
import { ContextQuizService } from './contextQuiz.service';
export * from './contextQuiz.serviceInterface';
export * from './contextSide.service';
import { ContextSideService } from './contextSide.service';
export * from './contextSide.serviceInterface';
export * from './contextStories.service';
import { ContextStoriesService } from './contextStories.service';
export * from './contextStories.serviceInterface';
export * from './contextTechniqueProgress.service';
import { ContextTechniqueProgressService } from './contextTechniqueProgress.service';
export * from './contextTechniqueProgress.serviceInterface';
export * from './contextTechniqueTargeting.service';
import { ContextTechniqueTargetingService } from './contextTechniqueTargeting.service';
export * from './contextTechniqueTargeting.serviceInterface';
export * from './contributor.service';
import { ContributorService } from './contributor.service';
export * from './contributor.serviceInterface';
export * from './curriculum.service';
import { CurriculumService } from './curriculum.service';
export * from './curriculum.serviceInterface';
export * from './decisionCollection.service';
import { DecisionCollectionService } from './decisionCollection.service';
export * from './decisionCollection.serviceInterface';
export * from './decisionFlow.service';
import { DecisionFlowService } from './decisionFlow.service';
export * from './decisionFlow.serviceInterface';
export * from './decisionNTX.service';
import { DecisionNTXService } from './decisionNTX.service';
export * from './decisionNTX.serviceInterface';
export * from './evaluation.service';
import { EvaluationService } from './evaluation.service';
export * from './evaluation.serviceInterface';
export * from './features.service';
import { FeaturesService } from './features.service';
export * from './features.serviceInterface';
export * from './flags.service';
import { FlagsService } from './flags.service';
export * from './flags.serviceInterface';
export * from './formation.service';
import { FormationService } from './formation.service';
export * from './formation.serviceInterface';
export * from './gamePlanner.service';
import { GamePlannerService } from './gamePlanner.service';
export * from './gamePlanner.serviceInterface';
export * from './invitations.service';
import { InvitationsService } from './invitations.service';
export * from './invitations.serviceInterface';
export * from './manageClaims.service';
import { ManageClaimsService } from './manageClaims.service';
export * from './manageClaims.serviceInterface';
export * from './manageRoles.service';
import { ManageRolesService } from './manageRoles.service';
export * from './manageRoles.serviceInterface';
export * from './manageUsers.service';
import { ManageUsersService } from './manageUsers.service';
export * from './manageUsers.serviceInterface';
export * from './monetization.service';
import { MonetizationService } from './monetization.service';
export * from './monetization.serviceInterface';
export * from './noDb.service';
import { NoDbService } from './noDb.service';
export * from './noDb.serviceInterface';
export * from './partner.service';
import { PartnerService } from './partner.service';
export * from './partner.serviceInterface';
export * from './payments.service';
import { PaymentsService } from './payments.service';
export * from './payments.serviceInterface';
export * from './positionals.service';
import { PositionalsService } from './positionals.service';
export * from './positionals.serviceInterface';
export * from './practicePlan.service';
import { PracticePlanService } from './practicePlan.service';
export * from './practicePlan.serviceInterface';
export * from './projectTools.service';
import { ProjectToolsService } from './projectTools.service';
export * from './projectTools.serviceInterface';
export * from './setup.service';
import { SetupService } from './setup.service';
export * from './setup.serviceInterface';
export * from './sim.service';
import { SimService } from './sim.service';
export * from './sim.serviceInterface';
export * from './simpleEvent.service';
import { SimpleEventService } from './simpleEvent.service';
export * from './simpleEvent.serviceInterface';
export * from './simpleMessage.service';
import { SimpleMessageService } from './simpleMessage.service';
export * from './simpleMessage.serviceInterface';
export * from './simpleSensor.service';
import { SimpleSensorService } from './simpleSensor.service';
export * from './simpleSensor.serviceInterface';
export * from './siteServices.service';
import { SiteServicesService } from './siteServices.service';
export * from './siteServices.serviceInterface';
export * from './sportsQuotes.service';
import { SportsQuotesService } from './sportsQuotes.service';
export * from './sportsQuotes.serviceInterface';
export * from './teams.service';
import { TeamsService } from './teams.service';
export * from './teams.serviceInterface';
export * from './techniqueAccessibility.service';
import { TechniqueAccessibilityService } from './techniqueAccessibility.service';
export * from './techniqueAccessibility.serviceInterface';
export * from './techniqueAchievement.service';
import { TechniqueAchievementService } from './techniqueAchievement.service';
export * from './techniqueAchievement.serviceInterface';
export * from './techniqueNotes.service';
import { TechniqueNotesService } from './techniqueNotes.service';
export * from './techniqueNotes.serviceInterface';
export * from './techniqueRelationships.service';
import { TechniqueRelationshipsService } from './techniqueRelationships.service';
export * from './techniqueRelationships.serviceInterface';
export * from './techniqueSeries.service';
import { TechniqueSeriesService } from './techniqueSeries.service';
export * from './techniqueSeries.serviceInterface';
export * from './techniques.service';
import { TechniquesService } from './techniques.service';
export * from './techniques.serviceInterface';
export * from './tenancy.service';
import { TenancyService } from './tenancy.service';
export * from './tenancy.serviceInterface';
export * from './trashTalk.service';
import { TrashTalkService } from './trashTalk.service';
export * from './trashTalk.serviceInterface';
export * from './vCards.service';
import { VCardsService } from './vCards.service';
export * from './vCards.serviceInterface';
export * from './versionReleaseNotes.service';
import { VersionReleaseNotesService } from './versionReleaseNotes.service';
export * from './versionReleaseNotes.serviceInterface';
export * from './weatherForecast.service';
import { WeatherForecastService } from './weatherForecast.service';
export * from './weatherForecast.serviceInterface';
export const APIS = [AdministrationService, AppRoutingService, AuthenticatorService, AuthorizationService, AutocompleteService, BetaFeaturesService, BodyService, ContactMeService, ContactsService, ContextAccessibiltyService, ContextAutocompleteService, ContextEquipmentService, ContextGlossaryService, ContextHelpService, ContextLinkService, ContextMediaService, ContextMetricsService, ContextNotesService, ContextQuizService, ContextSideService, ContextStoriesService, ContextTechniqueProgressService, ContextTechniqueTargetingService, ContributorService, CurriculumService, DecisionCollectionService, DecisionFlowService, DecisionNTXService, EvaluationService, FeaturesService, FlagsService, FormationService, GamePlannerService, InvitationsService, ManageClaimsService, ManageRolesService, ManageUsersService, MonetizationService, NoDbService, PartnerService, PaymentsService, PositionalsService, PracticePlanService, ProjectToolsService, SetupService, SimService, SimpleEventService, SimpleMessageService, SimpleSensorService, SiteServicesService, SportsQuotesService, TeamsService, TechniqueAccessibilityService, TechniqueAchievementService, TechniqueNotesService, TechniqueRelationshipsService, TechniqueSeriesService, TechniquesService, TenancyService, TrashTalkService, VCardsService, VersionReleaseNotesService, WeatherForecastService];
