/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AutocompleteItemModel } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AutocompleteServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Returns a list of users (email, preferred name) given an email address.
     * 
     * @param Filter 
     */
    getExactEmailAddress(Filter?: string, extraHttpRequestParams?: any): Observable<Array<AutocompleteItemModel>>;

    /**
     * Returns a list of users (username, preferred full name) given an exact username.
     * 
     * @param Filter 
     */
    getExactUserName(Filter?: string, extraHttpRequestParams?: any): Observable<Array<AutocompleteItemModel>>;

    /**
     * Returns a list of users (userid/proper name) given a \&quot;starts with\&quot; string.
     * 
     * @param Filter 
     */
    getUserIDListFiltered(Filter?: string, extraHttpRequestParams?: any): Observable<Array<AutocompleteItemModel>>;

    /**
     * Returns a list of users (username/proper name) given a \&quot;starts with\&quot; string.
     * 
     * @param Filter 
     */
    getUsernameListFiltered(Filter?: string, extraHttpRequestParams?: any): Observable<Array<AutocompleteItemModel>>;

}
