/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ContextAutoComplete } from '../model/models';
import { ContextAutoCompleteSearchParameters } from '../model/models';
import { ContextFilterEntry } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ContextAutocompleteServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param ContextAutoCompleteSearchParameters 
     */
    contextAutocompleteSearchByName(ContextAutoCompleteSearchParameters?: ContextAutoCompleteSearchParameters, extraHttpRequestParams?: any): Observable<Array<ContextAutoComplete>>;

    /**
     * 
     * 
     */
    filterlist(extraHttpRequestParams?: any): Observable<Array<ContextFilterEntry>>;

}
