/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CommonResult } from '../model/models';
import { ContextHelp } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ContextHelpServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param Context 
     * @param ContextKey 
     */
    contextHelpDeleteContext(Context?: string, ContextKey?: number, extraHttpRequestParams?: any): Observable<CommonResult>;

    /**
     * 
     * 
     * @param ContextHelpID 
     */
    contextHelpDeleteItem(ContextHelpID?: number, extraHttpRequestParams?: any): Observable<CommonResult>;

    /**
     * 
     * 
     * @param Context 
     * @param ContextKey 
     */
    contextHelpExists(Context?: string, ContextKey?: number, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * 
     * 
     * @param ContextHelp 
     */
    contextHelpInsert(ContextHelp?: ContextHelp, extraHttpRequestParams?: any): Observable<CommonResult>;

    /**
     * 
     * 
     * @param SearchText 
     */
    contextHelpSearch(SearchText?: string, extraHttpRequestParams?: any): Observable<Array<ContextHelp>>;

    /**
     * 
     * 
     * @param Context 
     * @param ContextKey 
     * @param SearchText 
     */
    contextHelpSearchContextWithText(Context?: string, ContextKey?: number, SearchText?: string, extraHttpRequestParams?: any): Observable<Array<ContextHelp>>;

    /**
     * 
     * 
     * @param Context 
     * @param ContextKey 
     */
    contextHelpSelectContext(Context?: string, ContextKey?: number, extraHttpRequestParams?: any): Observable<Array<ContextHelp>>;

    /**
     * 
     * 
     * @param ContextHelpID 
     */
    contextHelpSelectItem(ContextHelpID?: number, extraHttpRequestParams?: any): Observable<ContextHelp>;

    /**
     * 
     * 
     * @param ContextHelp 
     */
    contextHelpUpdate(ContextHelp?: ContextHelp, extraHttpRequestParams?: any): Observable<CommonResult>;

}
