/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Claim } from '../model/models';
import { IdentityResult } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ManageClaimsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param UserName 
     * @param ClaimType 
     * @param ClaimValue 
     */
    addClaimToUser(UserName?: string, ClaimType?: string, ClaimValue?: string, extraHttpRequestParams?: any): Observable<Claim>;

    /**
     * 
     * 
     * @param UserName 
     */
    getUserClaims(UserName?: string, extraHttpRequestParams?: any): Observable<Array<Claim>>;

    /**
     * 
     * 
     * @param UserName 
     * @param ClaimType 
     * @param ClaimValue 
     */
    removeClaimFromUser(UserName?: string, ClaimType?: string, ClaimValue?: string, extraHttpRequestParams?: any): Observable<IdentityResult>;

}
