/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AppIdentityUser } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SetupServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    configureAdminUser(extraHttpRequestParams?: any): Observable<number>;

    /**
     * 
     * 
     */
    configureFamilyUsers(extraHttpRequestParams?: any): Observable<number>;

    /**
     * 
     * 
     */
    configureRoles(extraHttpRequestParams?: any): Observable<number>;

    /**
     * 
     * 
     * @param sNameLast 
     * @param sNameFirst 
     * @param ContentMatch 
     * @param CaseMatch 
     */
    findUserFromSetup(sNameLast?: string, sNameFirst?: string, ContentMatch?: boolean, CaseMatch?: boolean, extraHttpRequestParams?: any): Observable<Array<AppIdentityUser>>;

    /**
     * 
     * 
     * @param UserName 
     */
    getUser(UserName?: string, extraHttpRequestParams?: any): Observable<AppIdentityUser>;

    /**
     * 
     * 
     */
    getUsersFromSetup(extraHttpRequestParams?: any): Observable<Array<AppIdentityUser>>;

}
