/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CommonResult } from '../model/models';
import { FieldSize } from '../model/models';
import { Formation } from '../model/models';
import { FormationElement } from '../model/models';
import { FormationPoint } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SimServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param SportID 
     */
    fieldSizeSelectAll(SportID?: number, extraHttpRequestParams?: any): Observable<Array<FieldSize>>;

    /**
     * 
     * 
     * @param FormationID 
     */
    formationDelete(FormationID?: number, extraHttpRequestParams?: any): Observable<CommonResult>;

    /**
     * 
     * 
     * @param FormationID 
     */
    formationElementSelectFormation(FormationID?: number, extraHttpRequestParams?: any): Observable<Array<FormationElement>>;

    /**
     * 
     * 
     * @param FormationElement 
     */
    formationElementsBulkUpdate(FormationElement?: Array<FormationElement>, extraHttpRequestParams?: any): Observable<CommonResult>;

    /**
     * 
     * 
     * @param ElemID 
     */
    formationElementsDelete(ElemID?: number, extraHttpRequestParams?: any): Observable<CommonResult>;

    /**
     * 
     * 
     * @param FormationElement 
     */
    formationElementsInsert(FormationElement?: FormationElement, extraHttpRequestParams?: any): Observable<CommonResult>;

    /**
     * 
     * 
     * @param FormationElement 
     */
    formationElementsUpdate(FormationElement?: FormationElement, extraHttpRequestParams?: any): Observable<CommonResult>;

    /**
     * 
     * 
     * @param Formation 
     */
    formationInsert(Formation?: Formation, extraHttpRequestParams?: any): Observable<CommonResult>;

    /**
     * 
     * 
     * @param FormationPoint 
     */
    formationPointsBulkUpdate(FormationPoint?: Array<FormationPoint>, extraHttpRequestParams?: any): Observable<CommonResult>;

    /**
     * 
     * 
     * @param FormationID 
     */
    formationPointsSelectFormation(FormationID?: number, extraHttpRequestParams?: any): Observable<Array<FormationPoint>>;

    /**
     * 
     * 
     * @param SportID 
     * @param FieldSizeID 
     */
    formationSelectAllByCriteria(SportID?: number, FieldSizeID?: number, extraHttpRequestParams?: any): Observable<Array<Formation>>;

    /**
     * 
     * 
     * @param FormationID 
     */
    formationSelectItem(FormationID?: number, extraHttpRequestParams?: any): Observable<Formation>;

    /**
     * 
     * 
     * @param Formation 
     */
    formationUpdate(Formation?: Formation, extraHttpRequestParams?: any): Observable<CommonResult>;

}
