/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CommonResult } from '../model/models';
import { TechniqueNote } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TechniqueNotesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Insert/Update a note.
     * 
     * @param TechniqueNote 
     */
    techniqueInsertUpdate(TechniqueNote?: TechniqueNote, extraHttpRequestParams?: any): Observable<CommonResult>;

    /**
     * Delete a note.
     * 
     * @param body 
     */
    techniqueNotesDeleteItem(body?: number, extraHttpRequestParams?: any): Observable<CommonResult>;

    /**
     * Delete all notes for a technique.
     * 
     * @param body 
     */
    techniqueNotesDeleteTechnique(body?: number, extraHttpRequestParams?: any): Observable<CommonResult>;

    /**
     * Select all the notes for a given technique.
     * 
     * @param TechniqueID 
     */
    techniqueNotesSelectTechnique(TechniqueID?: number, extraHttpRequestParams?: any): Observable<Array<TechniqueNote>>;

}
