/**
 * soccr.io API
 * An ASP.NET Core Web API for managing Soccer items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AccessibilityClass } from '../model/models';
import { AccessibilityTier } from '../model/models';
import { CommonResult } from '../model/models';
import { TechniqueAccessibility } from '../model/models';
import { TechniqueAccessibilityUpdate } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TechniqueAccessibilityServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    accessibilityClasses(extraHttpRequestParams?: any): Observable<Array<AccessibilityClass>>;

    /**
     * 
     * 
     */
    accessibilityTiers(extraHttpRequestParams?: any): Observable<Array<AccessibilityTier>>;

    /**
     * 
     * 
     * @param AccessibilityClassID 
     */
    accessibilityTiersForClass(AccessibilityClassID?: number, extraHttpRequestParams?: any): Observable<Array<AccessibilityTier>>;

    /**
     * 
     * 
     * @param TechniqueAccessibilityUpdate 
     */
    techniqueAccessibilityBulkInsertUpdate(TechniqueAccessibilityUpdate?: Array<TechniqueAccessibilityUpdate>, extraHttpRequestParams?: any): Observable<CommonResult>;

    /**
     * 
     * 
     * @param TechniqueAccessibility 
     */
    techniqueAccessibilityDelete(TechniqueAccessibility?: TechniqueAccessibility, extraHttpRequestParams?: any): Observable<CommonResult>;

    /**
     * 
     * 
     * @param body 
     */
    techniqueAccessibilityDeleteForTechnique(body?: number, extraHttpRequestParams?: any): Observable<CommonResult>;

    /**
     * 
     * 
     * @param TechniqueAccessibility 
     */
    techniqueAccessibilityInsertUpdate(TechniqueAccessibility?: TechniqueAccessibility, extraHttpRequestParams?: any): Observable<CommonResult>;

    /**
     * 
     * 
     * @param TechniqueID 
     */
    techniqueAccessibilitySelectAllInner(TechniqueID?: number, extraHttpRequestParams?: any): Observable<Array<TechniqueAccessibility>>;

    /**
     * 
     * 
     * @param TechniqueID 
     */
    techniqueAccessibilitySelectAllOuter(TechniqueID?: number, extraHttpRequestParams?: any): Observable<Array<TechniqueAccessibility>>;

    /**
     * 
     * 
     * @param TechniqueID 
     * @param TenantID 
     * @param UserID 
     */
    techniqueAccessibilityVerify(TechniqueID?: number, TenantID?: number, UserID?: number, extraHttpRequestParams?: any): Observable<{}>;

}
